name: NexEconomy
main: io.nexstudios.nexeconomy.NexEconomyPlugin
version: v1.0.0
api-version: "1.21"
author: NexStudios
load-before:
  - 'Essentials'
depend:
  - 'NexLogic'
softdepend:
  - 'Vault'
  - 'Towny'
libraries: []