# ######################################################  #
#                    LANGUAGE SETTINGS                     #
# ######################################################  #
# Here you can manage the general settings for the core plugin.
language: english

# ######################################################  #
#                     LOGGING SYSTEM                      #
# ######################################################  #
# The Debug Logging system for the core plugin
# You can enable or disable the debug logging system
# and set the debug level.
logging:
  debug:
    enable: false
    level: 3

# ######################################################  #
#                        PAYMENTS                         #
# ######################################################  #
# Here you can manage the player payments for each currency.
payments:
  - id: vault
    conditions:
      - id: permission
        world: 'nexeconomy.command.pay.vault'
        send-message: true
        as-actionbar: false
        message: '<dark_red><bold>ERROR</bold> <gray>» <red>You do not have permission to use Vault Payments.'
    min-amount-per-transaction: 10
    max-amount-per-transaction: 1000000
    cooldown: 10
    daily-limits:
      enable: true
      default:
        max-send: 500000
        max-receive: 1000000
      group:
        - max-send: 2500
          max-receive: 5000
          conditions:
            - id: permission
              permission: 'nexeconomy.command.pay.new-player'
        - max-send: 500000
          max-receive: 1000000
          conditions:
            - id: permission
              permission: 'nexeconomy.command.pay.trusted-player'
        - max-send: -1
          max-receive: -1
          conditions:
            - id: permission
              permission: 'nexeconomy.command.pay.mvp'